### ISSUE TITLE
why change the qrcode adhoc standard?

### ISSUE THREAD

**Issue by anarcat** [ModernPGP/QR#2]
i noticed that the chosen standard for the qrcode syntax (`pgp-fingerprint:...`) is different from any existing ones.

the pioneer in this domain, Monkeysign, seems to have established `OPENPGP4FPR:` as a well known prefix. it has been reused by OpenKeyChain on android, for example. [geysigning](https://github.com/muelli/geysigning) also uses that prefix and in fact expects it in scanned qrcodes. it is unclear if OpenKeyChain will accept qrcodes with a different prefix.

who exactly is expected to use that new prefix? what do we do with the implementations that _expect_ the other prefix?

monkeysign deals well with _any_ prefix, actually: it treats any 10 blocks of 4 hexadecimal digits (separated by zero or more spaces) as a fingerprint and just hopes for the best from there, so it can tolerate weird prefixes from other implementations, but i am hesitant in changing the prefix _generated_ in monkeysign for interoperability reasons. if i start using this standard, it may break interoperability with openkeychain, for example.

if a compelling case is made that the new standard is better, i'd be happy to change my mind, but the change seems needlessly gratituous so far.

thanks for any feedback.

**Comment by dschuermann** [comment]
Actually, this repo is abandoned AFAIK. We, at OpenKeychain, found similar problems with the `pgp-fingerprint` scheme, we proposed earlier. So we never actually implemented it. Currently only `OPENPGP4FPR` is used.

**Comment by anarcat** [comment]
okay, so i'll make a PR to remove the proposal then.

i don't understand why you say this is abandoned - it is linked from the frontpage of the modernpgp web page...

**Comment by dschuermann** [comment]
I simply don't know of any implementation that uses this proposal, that's why I consider it abandoned. I myself and @bnvk came up with the alternative scheme.

**Comment by anarcat** [comment]
understood, thanks for clarifying all this, and glad to see we stuck with the existing standard instead of creating a new one (even though it's uglier ;).

to be honest, i have absolutely no clue how we came up with that string: i assume it was generated in the earlier discussions between @lavamind, @dkg and myself, as it is in the first prototype that was committed in Monkeysign's history in 2010. so i can only blame myself for letting it live to this point if i find it ugly. :)
